	NOLIST
;=============================================================
; key.asm キー入力ライブラリ
;=============================================================
	LIST
GET_KEY:
 KEY_NOW_H	SET	(P1KEY)
 KEY_NOW_L	SET	(P1KEY+1)
 KEY_OLD_H	SET	(P1KEY_OLD)
 KEY_OLD_L	SET	(P1KEY_OLD+1)
 KEY_TRG_H	SET	(P1KEY_TRG)
 KEY_TRG_L	SET	(P1KEY_TRG+1)
 PAD_READ_ADDR	SET	(P1PADDLE)
 PAD_READ_ERR	SET	(0ffh)
 PAD_INIT	SET	(080h)
 PAD_NEUTRAL_LIMIT_L	SET	(030h)
 PAD_NEUTRAL_LIMIT_H	SET	(0a0h)
 BTN_READ_LEFT	SET	(P1LEFTKEYS)
 BTN_READ_MIDDLE	SET	(P1MIDDLEKEYS)
 BTN_READ_RIGHT	SET	(P1RIGHTKEYS)
 BTN_READ_MASK	SET	(0fh)
	STRING	LOCAL_LABEL
 LOCAL_LABEL	SET	"GET_KEY1"
	include	"./system/lib/get_key_sub.asm"

 KEY_NOW_H	SET	(P2KEY)
 KEY_NOW_L	SET	(P2KEY+1)
 KEY_OLD_H	SET	(P2KEY_OLD)
 KEY_OLD_L	SET	(P2KEY_OLD+1)
 KEY_TRG_H	SET	(P2KEY_TRG)
 KEY_TRG_L	SET	(P2KEY_TRG+1)
 PAD_READ_ADDR	SET	(P2PADDLE)
 PAD_READ_ERR	SET	(0ffh)
 PAD_INIT	SET	(080h)
 PAD_NEUTRAL_LIMIT_L	SET	(030h)
 PAD_NEUTRAL_LIMIT_H	SET	(0a0h)
 BTN_READ_LEFT	SET	(P2LEFTKEYS)
 BTN_READ_MIDDLE	SET	(P2MIDDLEKEYS)
 BTN_READ_RIGHT	SET	(P2RIGHTKEYS)
 BTN_READ_MASK	SET	(0fh)
	;STRING	LOCAL_LABEL
 LOCAL_LABEL	SET	"GET_KEY2"
	include	"./system/lib/get_key_sub.asm"

	retc,un

	end
